"""RC-00 · env_check phải đo được ĐIỀU KIỆN THOÁT của RC2-006.

Bối cảnh: tài liệu bàn giao ghi tiêu chí "lock_matches_installed = true", nhưng
`tools/env_check.py` KHÔNG hề đo trường đó — tiêu chí không đo được bằng công
cụ có sẵn. Bộ test này khoá cả hai thứ vừa bổ sung:

1. so `requirements.lock` với gói ĐANG CÀI THẬT;
2. tách `source_tree_dirty` (tệp tracked bị sửa) khỏi tệp untracked, vì trước
   đó một tệp `.md` ở gốc repo cũng bật cờ dirty — vừa báo động giả, vừa che
   mất trường hợp nguy hiểm thật (tệp `.py` lạ trong `src/`).
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
_SPEC = importlib.util.spec_from_file_location(
    "env_check_mod", ROOT / "tools" / "env_check.py")
env_check = importlib.util.module_from_spec(_SPEC)
sys.modules["env_check_mod"] = env_check
_SPEC.loader.exec_module(env_check)


# ── phân loại cây làm việc bẩn ────────────────────────────────────────────

def test_tep_md_o_goc_repo_KHONG_lam_cay_ban():
    """Đây là báo động giả đã gặp thật: `DATA_INPUT_REVIEW_FOR_MENTOR.md`
    untracked làm `source_tree_dirty=True` dù 0 tệp tracked bị sửa."""
    d = env_check._classify_dirty("?? DATA_INPUT_REVIEW_FOR_MENTOR.md")
    assert d["tracked"] == []
    assert d["untracked_source"] == []
    assert d["untracked_other"] == ["DATA_INPUT_REVIEW_FOR_MENTOR.md"]


def test_tep_py_la_trong_src_LA_NGUY_HIEM():
    """Tệp chưa commit trong `src/` không vào `source_hash` nhưng vẫn import
    được lúc build — bản dựng sẽ không tái lập được."""
    d = env_check._classify_dirty("?? src/text2pandas/pipelines/a6/hotfix.py")
    assert d["untracked_source"] == ["src/text2pandas/pipelines/a6/hotfix.py"]
    assert d["untracked_other"] == []


def test_tep_tracked_bi_sua_thi_cay_ban():
    d = env_check._classify_dirty(" M src/text2pandas/pipelines/a6/release.py\nM  configs/a.yaml")
    assert set(d["tracked"]) == {"src/text2pandas/pipelines/a6/release.py", "configs/a.yaml"}
    assert d["untracked_source"] == [] and d["untracked_other"] == []


def test_doi_ten_lay_ve_dich():
    d = env_check._classify_dirty("R  tools/old.py -> tools/new.py")
    assert d["tracked"] == ["tools/new.py"]


def test_porcelain_rong():
    for empty in (None, "", "\n\n"):
        d = env_check._classify_dirty(empty)
        assert d == {"tracked": [], "untracked_source": [], "untracked_other": []}


# ── đọc lock ──────────────────────────────────────────────────────────────

def test_doc_duoc_lock_kieu_pip_compile_co_hash(tmp_path):
    lock = tmp_path / "requirements.lock"
    lock.write_text(
        "#\n# This file is autogenerated by pip-compile with Python 3.11\n#\n"
        "pandas==2.3.3 \\\n"
        "    --hash=sha256:aaaa \\\n"
        "    --hash=sha256:bbbb\n"
        "pytest==9.1.1 \\\n"
        "    --hash=sha256:cccc\n", encoding="utf-8")
    info = env_check._parse_lock(lock)
    assert info["pins"] == {"pandas": "2.3.3", "pytest": "9.1.1"}
    assert info["n_hashes"] == 3


def test_doc_duoc_lock_pin_tran_khong_hash(tmp_path):
    lock = tmp_path / "requirements.lock"
    lock.write_text("# ghi chú\npandas==2.3.3\nPyYAML==6.0.3\n", encoding="utf-8")
    info = env_check._parse_lock(lock)
    assert info["pins"] == {"pandas": "2.3.3", "pyyaml": "6.0.3"}
    assert info["n_hashes"] == 0


def test_lock_khong_hash_thi_KHONG_phai_frozen(tmp_path):
    lock = tmp_path / "requirements.lock"
    lock.write_text("pandas==2.3.3\n", encoding="utf-8")
    rep = env_check._lock_report(lock)
    assert rep["lock_has_hashes"] is False
    assert "require-hashes" in rep["lock_note"]


def test_khong_co_lock_thi_matches_la_None_chu_khong_phai_False(tmp_path):
    """None = chưa đo được. False = đo rồi và lệch. Gộp hai cái là nói dối."""
    rep = env_check._lock_report(tmp_path / "khong-ton-tai.lock")
    assert rep["lock_exists"] is False
    assert rep["lock_matches_installed"] is None


def test_lock_lech_phien_ban_thi_bao_lech(tmp_path):
    lock = tmp_path / "requirements.lock"
    lock.write_text("pytest==0.0.1 --hash=sha256:aa\n", encoding="utf-8")
    rep = env_check._lock_report(lock)
    assert rep["lock_matches_installed"] is False
    assert any("pytest" in m for m in rep["lock_mismatches"])


def test_lock_khop_thi_bao_khop(tmp_path):
    ver = env_check._installed_version("pytest")
    if ver is None:
        pytest.skip("pytest không đọc được metadata trong môi trường này")
    lock = tmp_path / "requirements.lock"
    lock.write_text(f"pytest=={ver} --hash=sha256:aa\n", encoding="utf-8")
    rep = env_check._lock_report(lock)
    assert rep["lock_matches_installed"] is True
    assert rep["lock_mismatches"] == []


def test_goi_trong_lock_ma_chua_cai_thi_KHONG_khop(tmp_path):
    lock = tmp_path / "requirements.lock"
    lock.write_text("khong-he-ton-tai-goi-nay==1.0 --hash=sha256:aa\n",
                    encoding="utf-8")
    rep = env_check._lock_report(lock)
    assert rep["lock_matches_installed"] is False
    assert "khong-he-ton-tai-goi-nay" in rep["lock_not_installed"]


def test_ten_goi_chuan_hoa_gach_duoi_thanh_gach_ngang(tmp_path):
    lock = tmp_path / "requirements.lock"
    lock.write_text("Some_Package==1.0\n", encoding="utf-8")
    assert env_check._parse_lock(lock)["pins"] == {"some-package": "1.0"}


def test_extras_trong_ten_goi_bi_bo_di(tmp_path):
    """`coverage[toml]==7.0` — extras không thuộc tên phân phối. Giữ nguyên thì
    tra metadata trượt và gói bị báo nhầm là CHƯA CÀI."""
    lock = tmp_path / "requirements.lock"
    lock.write_text("coverage[toml]==7.0\n", encoding="utf-8")
    assert env_check._parse_lock(lock)["pins"] == {"coverage": "7.0"}


# ── hồi quy: khoảng trắng cột 1 của porcelain ─────────────────────────────

def test_dong_dau_mat_khoang_trang_van_lay_dung_duong_dan():
    """Bug thật, chỉ hiện ở DÒNG ĐẦU nên nó sống sót qua cả log lẫn mắt người.

    `_sh()` từng `.strip()` mọi output, kể cả `git status --porcelain`. Với
    porcelain, hai ký tự đầu là TRƯỜNG TRẠNG THÁI: dòng ` M configs/a.yaml`
    có một khoảng trắng ở cột 1. `.strip()` ăn mất nó ở dòng đầu tiên, và bộ
    tách cắt cứng từ cột 3 khi đó lệch một ký tự → `onfigs/a.yaml`.

    Hệ quả không phải mỹ quan: đường dẫn hỏng không còn khớp `SOURCE_PATHS`,
    nên một tệp lạ trong `configs/` có thể bị xếp nhầm thành `untracked_other`
    và KHÔNG chặn build.
    """
    d = env_check._classify_dirty("M  configs/a.yaml\n M src/text2pandas/pipelines/a6/b.py")
    assert set(d["tracked"]) == {"configs/a.yaml", "src/text2pandas/pipelines/a6/b.py"}


def test_untracked_dong_dau_van_duoc_xep_vao_duong_dan_nguon():
    d = env_check._classify_dirty("?? configs/lac.yaml\n?? README-lac.md")
    assert d["untracked_source"] == ["configs/lac.yaml"]
    assert d["untracked_other"] == ["README-lac.md"]


def test_sh_co_che_do_KHONG_strip_cho_porcelain():
    """Sửa ở bộ tách thôi là chưa đủ — nguồn dữ liệu phải thôi bóp méo."""
    out = env_check._sh("printf", " M configs/a.yaml\\n", strip=False)
    assert out == " M configs/a.yaml"
    assert env_check._sh("printf", " M configs/a.yaml\\n") == "M configs/a.yaml"


def test_main_goi_porcelain_voi_strip_False():
    src = (ROOT / "tools" / "env_check.py").read_text(encoding="utf-8")
    assert '_sh("git", "status", "--porcelain", strip=False)' in src


# ── RC2-021 được đo NGAY Ở LỆNH ĐẦU TIÊN ──────────────────────────────────

def test_env_check_co_do_lock_co_phu_het_import_khong():
    """Nếu chỉ có test kiểm điều này thì người review vẫn phải chạy hết suite
    mới biết venv của mình thiếu gói. `dp-env-check` là lệnh đầu tiên họ chạy,
    nên nó phải trả lời được — và phải FAIL, không phải warn."""
    rep = env_check._imports_report(ROOT)
    assert rep.get("lock_covers_imports") is True, rep
    src = (ROOT / "tools" / "env_check.py").read_text(encoding="utf-8")
    assert 'imprep.get("lock_covers_imports") is False' in src
    i = src.index('imprep.get("lock_covers_imports") is False')
    assert "fail.append" in src[i:i + 400], "phải là FAIL, không phải warn"


# ── RC2-038 · công cụ phải THI HÀNH điều kiện nó khai ─────────────────────

def test_source_tree_dirty_la_FAIL_chu_khong_phai_canh_bao():
    """`configs/execution_sequence_v1.yaml` khai `source_tree_dirty = false` là
    ĐIỀU KIỆN THOÁT của bước `env_check`. Trước RC2-038 nó chỉ là cảnh báo, nên
    `dp-env-check` in "✓ RC-00 env-check đạt" và thoát 0 trong khi vi phạm đúng
    tiêu chí nó vừa in.

    Đã xảy ra thật: bản dựng `5ffc07216708d9fd` sinh ra từ cây có 19 tệp tracked
    bị sửa, không có gì chặn lại.
    """
    src = (ROOT / "tools" / "env_check.py").read_text(encoding="utf-8")
    i = src.index('if info["source_tree_dirty"]:')
    khoi = src[i:i + 500]
    assert "fail.append" in khoi, "vẫn là cảnh báo, không phải cổng"
    assert "warn.append" not in khoi


def test_dieu_kien_thoat_trong_hop_dong_khop_voi_thi_hanh():
    """Hai chiều: mọi tiêu chí `env_check` khai trong execution_sequence phải
    có chỗ thi hành trong mã."""
    import yaml
    seq = yaml.safe_load(
        (ROOT / "configs" / "execution_sequence_v1.yaml").read_text(encoding="utf-8"))
    crit = " ".join(
        {s["id"]: s for s in seq["steps"]}["env_check"]["exit_criteria"])
    src = (ROOT / "tools" / "env_check.py").read_text(encoding="utf-8")
    for khoa in ("source_tree_dirty", "untracked_in_source_paths",
                 "lock_matches_installed", "lock_has_hashes",
                 "lock_covers_imports"):
        assert khoa in crit, f"hợp đồng không khai {khoa}"
        assert khoa in src, f"mã không đo {khoa}"


# ── RC2-052 · `--json` phải cho stdout là JSON THUẦN ──────────────────────
#
# Lỗi thật: dòng kết luận "✓ RC-00 env-check đạt" in ra stdout SAU khối JSON,
# nên `env_check.py --json > env_check.json` sinh ra tệp mà `json.load()`
# không đọc nổi ("Extra data: line 43"). Nó chỉ hỏng ở đường THÀNH CÔNG — khi
# env-check fail thì dòng kết luận đi stderr nên tệp lại hợp lệ. Một tệp bằng
# chứng chỉ hỏng lúc mọi thứ đều ổn là loại hỏng khó thấy nhất, và nó đã lọt
# vào gói bằng chứng §5.2 một lần.

def _run_json():
    import subprocess
    return subprocess.run([sys.executable, str(ROOT / "tools" / "env_check.py"), "--json"],
                          capture_output=True, text=True, cwd=ROOT, timeout=300)


def test_json_thuan_khong_lan_chu():
    import json
    json.loads(_run_json().stdout)      # JSONDecodeError nếu có chữ lẫn vào


def test_dong_ket_luan_van_noi_ra_o_stderr():
    """Đẩy khỏi stdout thì phải VẪN NÓI RA — không được nuốt mất."""
    r = _run_json()
    assert "RC-00" in r.stderr, "kết luận biến mất khỏi cả hai luồng"
