"""Domain contracts for Semantic Query Engine v3.

This package is deliberately free of corpus I/O and third-party dependencies.
All outer layers communicate through the immutable values exported here.
"""

from .ast import (
    Aggregate,
    Arithmetic,
    Comparison,
    Exists,
    Filter,
    FormulaCall,
    Literal,
    LogicalPredicate,
    MetricBindingHint,
    MetricRef,
    QuantifiedPredicate,
    QuestionAST,
    Rank,
    RollingAverage,
    RollingGrowth,
    SelectAtArg,
    Unary,
    expression_from_dict,
    expression_to_dict,
    iter_metric_refs,
)
from .types import (
    AggregateFunction,
    ArithmeticOperator,
    Axis,
    Basis,
    ComparisonOperator,
    Dimension,
    LogicalOperator,
    ObservationColumnRole,
    ObservationRoleSpec,
    ObservationRowRole,
    ObservationSignMode,
    OutputSpec,
    PeriodSemantics,
    PredicateQuantifier,
    RankDirection,
    ResultKind,
    UnaryOperator,
    UnitSpec,
)
from .validate import SemanticIssue, validate_question_ast

__all__ = [
    "Aggregate",
    "AggregateFunction",
    "Arithmetic",
    "ArithmeticOperator",
    "Axis",
    "Basis",
    "Comparison",
    "ComparisonOperator",
    "Dimension",
    "Exists",
    "Filter",
    "FormulaCall",
    "Literal",
    "LogicalOperator",
    "LogicalPredicate",
    "ObservationColumnRole",
    "ObservationRoleSpec",
    "ObservationRowRole",
    "ObservationSignMode",
    "MetricBindingHint",
    "MetricRef",
    "OutputSpec",
    "PeriodSemantics",
    "PredicateQuantifier",
    "QuantifiedPredicate",
    "QuestionAST",
    "Rank",
    "RankDirection",
    "ResultKind",
    "RollingAverage",
    "RollingGrowth",
    "SelectAtArg",
    "SemanticIssue",
    "Unary",
    "UnaryOperator",
    "UnitSpec",
    "expression_from_dict",
    "expression_to_dict",
    "iter_metric_refs",
    "validate_question_ast",
]
