#!/usr/bin/env bash
# Kế hoạch commit D1(a) — SINH TỰ ĐỘNG bởi tools/build_commit_plan_v1.py
# ĐỌC TRƯỚC KHI CHẠY. Đây là đề xuất, không phải lệnh đã được duyệt.
#
# Thứ tự bắt buộc theo doc 140 §2.7:
#   1. baseline source/config/test  ← neo mọi thứ về sau
#   2. tài liệu
#   3. preregistration  ← PHẢI trước lần đo đầu tiên
#   4. artifact sinh ra (cân nhắc .gitignore thay vì commit)
#
# HEAD hiện tại: fbd36c8f3e187686a99cd5a574cba475f53e0d8b
# Tổng path đang thay đổi: 429

set -euo pipefail
cd "$(dirname "$0")/.."

# ── 0 · rác, KHÔNG commit ───────────────────────────────────────────
# tools/vplus_refs.py.bak

# ── 1 · baseline source/config/test ────────────────────────────────
git add 'configs/execution/a6_identity.yaml'
git add 'configs/execution/formula_registry_v1.yaml'
git add 'configs/execution/metric_registry_v1.yaml'
git add 'configs/execution/promotion_rule_v1.yaml'
git add 'configs/execution/unit_scale_overrides_v1.json'
git add 'configs/retrieval/company_brand_attested_v1.yaml'
git add 'configs/retrieval/eval_v1.yaml'
git add 'src/retrieval/alias_store.py'
git add 'src/retrieval/evalkit/ck_list.py'
git add 'src/retrieval/evalkit/cli.py'
git add 'src/retrieval/evalkit/diag_nogold.py'
git add 'src/retrieval/evalkit/goldkit.py'
git add 'src/retrieval/evalkit/goldset.py'
git add 'src/retrieval/evalkit/metrics.py'
git add 'src/retrieval/evalkit/migrate_ck.py'
git add 'src/retrieval/evalkit/report.py'
git add 'src/retrieval/evalkit/runner.py'
git add 'src/retrieval/evalkit/stages.py'
git add 'src/retrieval/pipeline.py'
git add 'src/retrieval/query_terms.py'
git add 'src/retrieval/rank_s2.py'
git add 'src/retrieval/submission_adapter.py'
git add 'tests/execution/test_p0_families_v1.py'
git add 'tests/expected_p0_cases.jsonl'
git add 'tests/expected_p0_cases.meta.json'
git add 'tests/test_answer_operation.py'
git add 'tests/test_entity_resolution_trace.py'
git add 'tests/test_evalkit_metrics.py'
git add 'tests/test_evalkit_pipeline_fixture.py'
git add 'tests/test_gold_pool_v4.py'
git add 'tests/test_gold_pool_v5.py'
git add 'tests/test_gold_tay_pool.py'
git add 'tests/test_h0_gates.py'
git add 'tests/test_integration_smoke.py'
git add 'tests/test_p0_unify.py'
git add 'tests/test_p0e_audit_nam_khong_leakage.py'
git add 'tests/test_p0f_loc_cot_phi_gia_tri.py'
git add 'tests/test_p0g_so_hoc.py'
git add 'tests/test_s2_primary_prior.py'
git add 'tests/test_year_signal_not_evidence.py'
git add 'tools/answer_a6/01_resolver.py'
git add 'tools/answer_a6/02_kiem_bat_bien.py'
git add 'tools/answer_a6/03_doi_chieu.py'
git add 'tools/answer_a6/04_kiem_scale.py'
git add 'tools/answer_a6/05_audit_nhan_thieu.py'
git add 'tools/answer_a6/06_dong_goi.py'
git add 'tools/answer_a6/07_bat_bien_goi.py'
git add 'tools/answer_a6/08_test_toi_gian.py'
git add 'tools/answer_a6/09_dung_h0.py'
git add 'tools/answer_a6/10_bao_cao_h0.py'
git add 'tools/answer_v2/01_dung_dap_an.py'
git add 'tools/answer_v2/02_do.py'
git add 'tools/answer_v2/03_dong_goi.py'
git add 'tools/answer_v2/04_doi_chieu_don_vi.py'
git add 'tools/answer_v2/05_kiem_tay_dap_an.py'
git add 'tools/answer_v2/06_loc_cot_phi_gia_tri.py'
git add 'tools/answer_v3/01_chon_bang_kiem_chung.py'
git add 'tools/answer_v3/02_dong_goi_v3.py'
git add 'tools/attest_brands.py'
git add 'tools/audit_nam/01_chon_mau.py'
git add 'tools/audit_nam/02_trich_nguon.py'
git add 'tools/audit_nam/03_phan_xu_ky.py'
git add 'tools/audit_nam/04_mau_kiem_tay.py'
git add 'tools/audit_nam/05_gold_audit.py'
git add 'tools/audit_nam/06_do.py'
git add 'tools/build_12step_map_v1.py'
git add 'tools/build_candidate_v1.py'
git add 'tools/build_commit_plan_v1.py'
git add 'tools/build_evidence_packet_133.py'
git add 'tools/build_expected_p0_cases_v1.py'
git add 'tools/build_label_dossier_v1.py'
git add 'tools/build_metric_registry_v1.py'
git add 'tools/build_qid_slices_v1.py'
git add 'tools/build_retrieval_workdb.sh'
git add 'tools/build_source_identity_v1.py'
git add 'tools/build_sync_packet_v2.py'
git add 'tools/build_unit_overrides_v1.py'
git add 'tools/c1_gate_calibration_v1.py'
git add 'tools/c1_gate_report_v1.py'
git add 'tools/ceiling_analysis_v1.py'
git add 'tools/chan_doan/audit_role_leakage.py'
git add 'tools/chan_doan/audit_year_leakage.py'
git add 'tools/chan_doan/do_tin_hieu.py'
git add 'tools/chan_doan/do_tran_rerank.py'
git add 'tools/chan_doan/lay_top60.py'
git add 'tools/crossmachine_check_v1.py'
git add 'tools/dev_label_status_v1.py'
git add 'tools/diag_slot_scoring_v1.py'
git add 'tools/eval_answer_v1.py'
git add 'tools/eval_gold_v2.py'
git add 'tools/evalkit'
git add 'tools/execution/__init__.py'
git add 'tools/execution/a6_identity.py'
git add 'tools/execution/answer_operation.py'
git add 'tools/execution/defect_register_primary_operation.py'
git add 'tools/execution/determinism_precheck_report.py'
git add 'tools/execution/dong_goi_c1r.py'
git add 'tools/execution/dong_goi_tat_dinh.py'
git add 'tools/execution/emit_arith_v1.py'
git add 'tools/execution/emit_lookup_v1.py'
git add 'tools/execution/fact_rank_v1.py'
git add 'tools/execution/generate_answer_operation_precheck.py'
git add 'tools/execution/joint_search_v1.py'
git add 'tools/execution/operand_pipeline_v1.py'
git add 'tools/execution/phan_xu_don_vi.py'
git add 'tools/execution/score_v2.py'
git add 'tools/execution/total_scope_audit.py'
git add 'tools/execution/unit_rule_v2.py'
git add 'tools/execution/unit_token_scan.py'
git add 'tools/execution/unit_token_scan_v2.py'
git add 'tools/execution/unit_token_scan_v3.py'
git add 'tools/execution/vong_phan_xu.py'
git add 'tools/fact_candidates_v1.py'
git add 'tools/fact_slot_report_v1.py'
git add 'tools/git_inventory_v1.py'
git add 'tools/gold_adjudicate_v2.py'
git add 'tools/gold_dap_an/01_chon_mau.py'
git add 'tools/gold_dap_an/02_phan_xu_o.py'
git add 'tools/gold_pool_ext_v1.py'
git add 'tools/gold_pool_v4.py'
git add 'tools/gold_pool_v5.py'
git add 'tools/gold_pool_v6.py'
git add 'tools/gold_sheet_v6.py'
git add 'tools/gold_tay.py'
git add 'tools/gold_tay_eval.py'
git add 'tools/human_audit.py'
git add 'tools/p0_before_after.py'
git add 'tools/pilot_labels_v1.py'
git add 'tools/question_plan_v1.py'
git add 'tools/reaudit/m10_calib.py'
git add 'tools/reaudit/m11_rank.py'
git add 'tools/reaudit/m12_doc.py'
git add 'tools/reaudit/m13_npolicy.py'
git add 'tools/reaudit/m14_agg.py'
git add 'tools/reaudit/m15_couple.py'
git add 'tools/reaudit/m1_baseline.py'
git add 'tools/reaudit/m2_entity.py'
git add 'tools/reaudit/m3_rc1.py'
git add 'tools/reaudit/m4_impact.py'
git add 'tools/reaudit/m5_cov.py'
git add 'tools/reaudit/m5b_cov.py'
git add 'tools/reaudit/m6_bias.py'
git add 'tools/reaudit/m6b.py'
git add 'tools/reaudit/m7_depth.py'
git add 'tools/reaudit/m8_ceiling.py'
git add 'tools/reaudit/m9_weight.py'
git add 'tools/reference_eval_v1.py'
git add 'tools/replay_submission_v1.py'
git add 'tools/retrieval_exp/e1_ceiling.py'
git add 'tools/retrieval_exp/e1_proxy_gap.py'
git add 'tools/retrieval_exp/e1_proxy_report.py'
git add 'tools/retrieval_exp/e2_build_evidence.py'
git add 'tools/retrieval_exp/e2_crossfit.py'
git add 'tools/retrieval_exp/e2_full_regression.py'
git add 'tools/retrieval_exp/e2_run.py'
git add 'tools/retrieval_exp/e2_score.py'
git add 'tools/retrieval_exp/e2_stage_boundary.py'
git add 'tools/retrieval_exp/e2_stats.py'
git add 'tools/rewrite_submission.py'
git add 'tools/run_arith_eval_v1.py'
git add 'tools/run_joint_ab_v1.py'
git add 'tools/run_oracle_table_v1.py'
git add 'tools/run_p0_suite_v1.py'
git add 'tools/run_scoring_ablation_v2.py'
git add 'tools/select_dev_audit_v1.py'
git add 'tools/so_hoc/01_phan_loai.py'
git add 'tools/so_hoc/02_engine.py'
git add 'tools/so_hoc/03_chay.py'
git add 'tools/so_hoc/04_truy_hoi_theo_o.py'
git add 'tools/so_hoc/05_kiem_bat_bien.py'
git add 'tools/so_hoc/06_kiem_tay.py'
git add 'tools/so_hoc/07_dong_goi.py'
git add 'tools/so_hoc/08_chay_test.py'
git add 'tools/so_hoc/09_do_tung_lop.py'
git add 'tools/submission_gate_v1.py'
git add 'tools/verify_no_behavior_change.py'
git add 'tools/vplus_build.py'
git add 'tools/vplus_calib.py'
git add 'tools/vplus_refs.py'
git commit -m "baseline(d1a): source/config/test trước vòng D1(a)"

# ── 2 · tài liệu ───────────────────────────────────────────────────
git add 'docs/100_FEEDBACK_AND_IMPLEMENTATION_DIRECTIVE_EXECUTION_065.md'
git add 'docs/101_REVIEW_DIRECTIVE_100.md'
git add 'docs/102_FEEDBACK_AND_REQUIRED_ACTIONS_FOR_C1_H0_CLOSURE.md'
git add 'docs/103_S4_A6_FIRST_AUDIT_VA_H0_REMEDIATION.md'
git add 'docs/104_REVIEW_AND_FEEDBACK_ON_103_H0_REMEDIATION.md'
git add 'docs/105_THIET_KE_unit_rule_v2_VA_ANSWER_OPERATION_GATE.md'
git add 'docs/106_FEEDBACK_TO_105_UNIT_RULE_V2_AND_ANSWER_OPERATION_DESIGN.md'
git add 'docs/107_THIET_KE_V2_unit_rule_v2_VA_answer_operation_gate.md'
git add 'docs/108_FEEDBACK_TO_107_DESIGN_V2_BEFORE_IMPLEMENTATION.md'
git add 'docs/109_THIET_KE_V3_unit_rule_v2_VA_operation_gate_v2.md'
git add 'docs/110_FEEDBACK_TO_109_AND_OP_EVIDENCE_AUDIT.md'
git add 'docs/111_REMEDIATION_REPORT_operation_gate_v3.md'
git add 'docs/112_FEEDBACK_TO_111_OPERATION_GATE_V3_AND_OP_EVIDENCE_V2.md'
git add 'docs/113_REMEDIATION_REPORT_operation_gate_v3_1.md'
git add 'docs/114_REVIEW_AND_FEEDBACK_ON_113_OPERATION_GATE_V3_1.md'
git add 'docs/115_OPERATION_SHADOW_AUDIT_VA_PURE_unit_rule_v2.md'
git add 'docs/117_SIGNOFF_COMPATIBILITY_GATE_VA_unit_rule_v2_1.md'
git add 'docs/118_RETRIEVAL_EVAL_VALIDITY_VA_TIEN_NGHIEM_LOP_BAO_CAO.md'
git add 'docs/119_COMPREHENSIVE_FEEDBACK_ON_117_AND_118.md'
git add 'docs/120_EXECUTION_REPORT_TREN_FEEDBACK_119.md'
git add 'docs/121_END_TO_END_ACCURACY_IMPROVEMENT_DIRECTIVE_AFTER_120.md'
git add 'docs/122_MASTER_PLAN_EXECUTION_ACCURACY_V2.md'
git add 'docs/123_REVIEW_AND_REQUIRED_CORRECTIONS_FOR_122_MASTER_PLAN.md'
git add 'docs/124_MASTER_PLAN_122_1_FINAL.md'
git add 'docs/125_COMPREHENSIVE_FEEDBACK_ON_124_MASTER_PLAN_122_1.md'
git add 'docs/126_D0_D3_EXECUTION_REPORT_BATCH_SIZE_AND_D4_PLAN.md'
git add 'docs/127_COMPREHENSIVE_REVIEW_OF_126_EXECUTION_STATUS_AND_SYNC_122_1.md'
git add 'docs/128_THI_HANH_REVIEW_127.md'
git add 'docs/129_AUDIT_HIEN_TRANG.md'
git add 'docs/130_COMPREHENSIVE_REVIEW_AND_OPTIMAL_EXECUTION_PLAN.md'
git add 'docs/131_REVIEW_AND_CORRECTIONS_FOR_130_OPTIMAL_EXECUTION_PLAN.md'
git add 'docs/132B_BREAKTHROUGH_EXECUTION_ACCURACY_STRATEGY.md'
git add 'docs/132_RESOLVE_REVIEW_131.md'
git add 'docs/133_REVIEW_132B_AND_OPTIMAL_MASTER_PLAN.md'
git add 'docs/134_COMPREHENSIVE_AUDIT_OF_132B_AND_133_MASTER_PLAN.md'
git add 'docs/135_EXECUTE_PLAN_133.md'
git add 'docs/136_PER_SLOT_SCORING_V2.md'
git add 'docs/137_DOC_LOG_12_BUOC.md'
git add 'docs/138_PLAN_D1A_PER_SLOT_SCORING.md'
git add 'docs/140_COMPREHENSIVE_REVIEW_AND_FEEDBACK_ON_137_138.md'
git add 'docs/71_CHON_MODEL_CHO_TUNG_TANG.md'
git add 'docs/72_FLOW_CHAY_FULL_LAY_KET_QUA_NOP.md'
git add 'docs/73_TRA_LOI_4_CAU_HOI_VA_SUA_LAI_KE_HOACH_NOP.md'
git add 'docs/74_DANH_GIA_TANG_RETRIEVAL_S0_S2.md'
git add 'docs/76_KHUNG_DANH_GIA_RETRIEVAL_KET_QUA.md'
git add 'docs/77_BA_CAN_THIEP_S2_KET_QUA.md'
git add 'docs/78_TECHNICAL_AUDIT_RETRIEVAL.md'
git add 'docs/79_P0_SUA_REGRESSION_VA_DO_LAI_1012.md'
git add 'docs/80_RETRIEVAL_P0_P1_GOLD_TAY_ADAPTER.md'
git add 'docs/81_P0a_GOLD_SHEET_VA_POOL_V3.md'
git add 'docs/82_P0_B_GOLD_TAY_ADJUDICATION.md'
git add 'docs/82_P0d_HUMAN_AUDIT_GOLD_TAY.md'
git add 'docs/83_P0_C_POOL_AND_ENTITY_TRACE.md'
git add 'docs/84_P0_D_READJUDICATION_V4.md'
git add 'docs/85_KET_QUA_NOP_THU_VA_CHAN_DOAN.md'
git add 'docs/86_CHAN_DOAN_LAN_NOP_2_VA_TRAN_RERANK.md'
git add 'docs/87_S3_YEAR_ROLE_RERANK.md'
git add 'docs/88_P0_E_NEUTRAL_YEAR_AUDIT.md'
git add 'docs/89_P0_F_TANG_DAP_AN.md'
git add 'docs/90_P0_G_ENGINE_SO_HOC.md'
git add 'docs/91_RETRIEVAL_FULL_REAUDIT.md'
git add 'docs/92_RETRIEVAL_MASTER_PLAN.md'
git add 'docs/93_RETRIEVAL_MASTER_PLAN_V2.md'
git add 'docs/94_GOLD_VALIDATION.md'
git add 'docs/95_VPLUS_CALIBRATION.md'
git add 'docs/96_ENGINEERING_REVIEW.md'
git add 'docs/97_A6_FACT_RESOLVER.md'
git add 'docs/97_ANSWER_LAYER_DIAGNOSIS.md'
git add 'docs/97_EXECUTION_ACCURACY_065_IMPROVEMENT_PLAN.md'
git add 'docs/98_REVIEW_PLAN_EXECUTION_065.md'
git add 'docs/99_PLAN_EXECUTION_065_V2.md'
git add 'docs/EXECUTION_STATUS.md'
git add 'docs/PREREGISTRATION_C1.md'
git add 'docs/RUNBOOK_NEXT_3.md'
git commit -m "docs(d1a): 137/138/140 + báo cáo thi hành"

# ── 3 · preregistration — neo vào baseline SHA ở bước 1 ───────────
git add 'docs/PREREGISTRATION_D1A.md'
git commit -m "prereg(d1a): đăng ký giả thuyết/ngưỡng TRƯỚC khi đo"

# ── 4 · artifact sinh ra ──────────────────────────────────────────
# ⚠️ CÂN NHẮC: artifact tái sinh được bằng lệnh. Commit chúng làm phình
#    lịch sử và dễ lệch với code. Lựa chọn khác: thêm vào .gitignore và
#    chỉ đóng gói trong packet evidence có MANIFEST.sha256.
#    Quyết định này là của người chủ repo — script để sẵn cả hai đường.
# git add 'evaluation/arith_traces_v1.jsonl'
# git add 'evaluation/fact_candidates_gold45_v10.jsonl'
# git add 'evaluation/fact_candidates_gold45_v11.jsonl'
# git add 'evaluation/fact_candidates_gold45_v12.jsonl'
# git add 'evaluation/operand_candidates_sample.jsonl'
# git add 'evaluation/qid_slices.json'
# git add 'evaluation/question_plans_1012.jsonl'
# git add 'evaluation/run_trace_1012.jsonl'
# git add 'identity/AUDIT_SELECTION_SEAL.json'
# git add 'identity/SOURCE_SELECTION.json'
# git add 'identity/access_log.json'
# git add 'identity/data_identity.json'
# git add 'identity/dirty_worktree_20260820.patch'
# git add 'identity/dirty_worktree_20260821.patch'
# git add 'identity/environment_identity.json'
# git add 'identity/final_audit_seal.json'
# git add 'identity/p0i_identity_resolution.json'
# git add 'identity/p0i_member_manifest.json'
# git add 'identity/source_identity.json'
# git add 'packet_kind.json'
# git add 'reports/12_step_execution_map.json'
# git add 'reports/arith_eval_v1.json'
# git add 'reports/c1_ablation_v1.json'
# git add 'reports/c1_ablation_v1_det.json'
# git add 'reports/c1_gate_calibration_v1.json'
# git add 'reports/c1_gate_report_C1e.json'
# git add 'reports/ceiling_analysis_v1.json'
# git add 'reports/clean_replay.json'
# git add 'reports/crossmachine/fact_slot__linux-aarch64-py3.10.12.json'
# git add 'reports/dev_label_status_v1.json'
# git add 'reports/diag_slot_scoring_v1.json'
# git add 'reports/fact_candidates_v1_recall.json'
# git add 'reports/fact_slot_evidence_v1.json'
# git add 'reports/git_inventory_v1.json'
# git add 'reports/joint_ab_v1.json'
# git add 'reports/labeling_batch_size_report.json'
# git add 'reports/labeling_batch_size_report_v2.json'
# git add 'reports/metric_audit_CARD.json'
# git add 'reports/metric_audit_V2.json'
# git add 'reports/metric_registry_v1_coverage.json'
# git add 'reports/oracle_table_v1.json'
# git add 'reports/p0_suite_v1.json'
# git add 'reports/paired_slices_v1.json'
# git add 'reports/primary_boost_verification.json'
# git add 'reports/question_plan_v1_report.json'
# git add 'reports/reference_eval_v1.json'
# git add 'reports/reviewer_replay_report.json'
# git add 'reports/run_trace_1012.jsonl'
# git add 'reports/scoring_ablation_v2.json'
# git add 'reports/submission_C1e_clean_replay.json'
# git add 'reports/submission_P0I_clean_replay.json'
# git add 'reports/submission_gate_v1.json'
# git add 'reports/validate_C1e.json'
# git add 'sync_122_2.sha256'
# git add 'sync_133_evidence.sha256'
# git commit -m "artifacts(d1a): báo cáo đo vòng D1(a)"

# ── 5 · dữ liệu ───────────────────────────────────────────────────
# git add 'data/curated/dev-legacy/audit/_log/p0e_execution_log.txt'
# git add 'data/curated/dev-legacy/audit/bang_tho.jsonl'
# git add 'data/curated/dev-legacy/audit/gold_audit_nam.jsonl'
# git add 'data/curated/dev-legacy/audit/kiem_tay_ket_qua.json'
# git add 'data/curated/dev-legacy/audit/mau_audit_nam.json'
# git add 'data/curated/dev-legacy/audit/mau_kiem_tay_dong_bang.json'
# git add 'data/curated/dev-legacy/audit/phan_xu_ky.jsonl'
# git add 'data/curated/dev-legacy/execution_gold/audit40_selection.json'
# git add 'data/curated/dev-legacy/execution_gold/dev60_labels.jsonl'
# git add 'data/curated/dev-legacy/execution_gold/dev60_selection.json'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0037.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0047.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0120.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0162.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0204.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0221.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0290.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0362.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0389.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0411.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0441.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0447.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0502.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0522.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0563.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0569.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0614.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0635.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0697.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0704.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0732.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0741.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0777.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0788.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0797.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0809.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0842.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0860.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0866.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0876.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0910.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0913.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0951.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0961.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0964.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0968.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_0995.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_1004.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_1010.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_audit40_blind/qid_1012.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0052.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0077.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0081.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0213.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0272.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0339.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0340.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0359.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0366.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0378.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0380.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0382.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0384.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0398.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0401.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0410.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0421.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0424.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0446.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0477.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0483.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0485.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0500.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0506.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0508.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0527.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0528.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0543.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0556.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0576.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0643.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0645.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0649.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0672.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0678.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0684.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0685.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0688.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0706.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0708.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0709.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0733.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0746.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0772.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0795.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0800.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0820.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0871.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0883.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0893.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0934.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0948.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0949.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0955.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0965.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0983.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0987.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0989.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0993.md'
# git add 'data/curated/dev-legacy/execution_gold/dossiers_dev60/qid_0994.md'
# git add 'data/curated/dev-legacy/execution_gold/label_template_schema.json'
# git add 'data/curated/dev-legacy/gold_dap_an/gold_dap_an_v1.jsonl'
# git add 'data/curated/dev-legacy/gold_dap_an/mau_v1.jsonl'
# git add 'data/curated/dev-legacy/gold_dap_an/worksheet_uncertain_v1.jsonl'
# git add 'data/curated/dev-legacy/gold_entity_override_v1.json'
# git add 'data/curated/dev-legacy/gold_sample_v1.jsonl'
# git add 'data/curated/dev-legacy/gold_tay_sample_v2.jsonl'
# git add 'data/curated/dev-legacy/gold_v1.jsonl'
# git add 'data/curated/dev-legacy/gold_v2.jsonl'

echo "Xong. Kiểm: git log --oneline -5"
